# Natural Language Processing

## Dataset: The Multilingual Amazon Reviews Corpus

This project is available in this [repository](https://github.com/ricardoleoncorreia/amazon-review-score-predictor) in GitHub.

Details about the dataset:
* It can be downloaded from [Kaggle](https://www.kaggle.com/datasets/mexwell/amazon-reviews-multi).
* Description of the data available in [AWS Open Data](https://registry.opendata.aws/amazon-reviews-ml/).
* [License](https://github.com/awslabs/open-data-docs/blob/main/LICENSE) for data usage.

To be able to use this notebook code, please create a `data` folder structure as mentioned in the read me file.

Let's start reviewing the content of the train, test and validation datasets:

In [18]:
import sys, os
sys.path.append(os.path.abspath('..'))  # Add project root to Python path

## Analyze raw data

### Training dataset

In [6]:
import pandas as pd

train_data_raw = pd.read_csv('../data/raw/train.csv')
train_data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 9 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Unnamed: 0        1200000 non-null  int64
 1   review_id         1200000 non-null  object
 2   product_id        1200000 non-null  object
 3   reviewer_id       1200000 non-null  object
 4   stars             1200000 non-null  int64
 5   review_body       1200000 non-null  object
 6   review_title      1199957 non-null  object
 7   language          1200000 non-null  object
 8   product_category  1200000 non-null  object
dtypes: int64(2), object(7)
memory usage: 82.4+ MB

In [7]:
print(f"Training data languages: {train_data_raw['language'].unique()}")
train_data_raw.head()

Training data languages: ['de' 'en' 'es' 'fr' 'ja' 'zh']

,Unnamed: 0,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,0,de_0203609,product_de_0865382,reviewer_de_0267719,1,Armband ist leider nach 1 Jahr kaputt gegangen,Leider nach 1 Jahr kaputt,de,sports
1,1,de_0559494,product_de_0678997,reviewer_de_0783625,1,In der Lieferung war nur Ein Akku!,EINS statt ZWEI Akkus!!!,de,home_improvement
2,2,de_0238777,product_de_0372235,reviewer_de_0911426,1,"Ein Stern, weil gar keine geht nicht. Es hande...",Achtung Abzocke,de,drugstore
3,3,de_0477884,product_de_0719501,reviewer_de_0836478,1,"Dachte, das wären einfach etwas festere Binden...",Zu viel des Guten,de,drugstore
4,4,de_0270868,product_de_0022613,reviewer_de_0736276,1,Meine Kinder haben kaum damit gespielt und nac...,Qualität sehr schlecht,de,toy

### Test dataset

In [10]:
test_data_raw = pd.read_csv('../data/raw/test.csv')
test_data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        30000 non-null  int64
 1   review_id         30000 non-null  object
 2   product_id        30000 non-null  object
 3   reviewer_id       30000 non-null  object
 4   stars             30000 non-null  int64
 5   review_body       30000 non-null  object
 6   review_title      29999 non-null  object
 7   language          30000 non-null  object
 8   product_category  30000 non-null  object
dtypes: int64(2), object(7)
memory usage: 2.1+ MB

In [11]:
print(f"Test data languages: {test_data_raw['language'].unique()}")
test_data_raw.head()

Test data languages: ['de' 'en' 'es' 'fr' 'ja' 'zh']

,Unnamed: 0,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,0,de_0784695,product_de_0572654,reviewer_de_0645436,1,"Leider, leider nach einmal waschen ausgebliche...",Leider nicht zu empfehlen,de,home
1,1,de_0759207,product_de_0567331,reviewer_de_0183703,1,zunächst macht der Anker Halter einen soliden ...,Gummierung nach 6 Monaten kaputt,de,wireless
2,2,de_0711785,product_de_0482105,reviewer_de_0182152,1,Siegel sowie Verpackung war beschädigt und war...,Flohmarkt ware,de,industrial_supplies
3,3,de_0964430,product_de_0616480,reviewer_de_0991563,1,Habe dieses Produkt NIE erhalten und das Geld ...,Katastrophe,de,industrial_supplies
4,4,de_0474538,product_de_0228702,reviewer_de_0316188,1,Die Träger sind schnell abgerissen,Reißverschluss klemmt,de,luggage

### Validation dataset

In [12]:
validation_data_raw = pd.read_csv('../data/raw/validation.csv')
validation_data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        30000 non-null  int64
 1   review_id         30000 non-null  object
 2   product_id        30000 non-null  object
 3   reviewer_id       30000 non-null  object
 4   stars             30000 non-null  int64
 5   review_body       30000 non-null  object
 6   review_title      29998 non-null  object
 7   language          30000 non-null  object
 8   product_category  30000 non-null  object
dtypes: int64(2), object(7)
memory usage: 2.1+ MB

In [13]:
print(f"Validation data languages: {validation_data_raw['language'].unique()}")
validation_data_raw.head()

Validation data languages: ['de' 'en' 'es' 'fr' 'ja' 'zh']

,Unnamed: 0,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,0,de_0591095,product_de_0301773,reviewer_de_0787123,1,Das Produkt kam bis heute nicht bei mir an. Ic...,Produkte NICHT geliefert,de,toy
1,1,de_0987834,product_de_0720578,reviewer_de_0983846,1,"Gebrauchte Spinner, teilzerlegt und teilweise ...","Gebrauchtware, ekelhaft",de,toy
2,2,de_0978206,product_de_0499114,reviewer_de_0238704,1,Bei beiden Bestellungen war jeweils eine Glühb...,Sehr schlechte Qualität,de,home
3,3,de_0407600,product_de_0648552,reviewer_de_0102048,1,Sofort zurückgeschickt,Der letzte Dreck,de,furniture
4,4,de_0453469,product_de_0900029,reviewer_de_0862313,1,wie man auf den Fotos erkennen kann ist das Gl...,"passform schlecht, Haftung schlecht - Finger weg",de,wireless

## Raw data transformation

As seen in the previous steps, there are two key points to do:

* Remove the fix column that contains indexes.
* Filter data to get only Spanish reviews (scope of the data analysis).

For that, we can use a helper function to do that for each dataset.

In [28]:
#import importlib
#from amazon_review_score_predictor import transform
#importlib.reload(transform)
from IPython.display import display
from amazon_review_score_predictor.transform import filter_dataset_by_language

all_stats = [filter_dataset_by_language(filename=filename, language='es') for filename in ['train', 'test', 'validation']]
display(pd.DataFrame(all_stats))

Processing train.csv...
Processing test.csv...
Processing validation.csv...

     filename  original_records  filtered_records  percentage unique_languages
0       train           1200000            200000       16.67             [es]
1        test             30000              5000       16.67             [es]
2  validation             30000              5000       16.67             [es]

In [29]:
train_data = pd.read_csv('../data/processed/train.csv')
train_data.head()

,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,es_0491108,product_es_0296024,reviewer_es_0999081,1,Nada bueno se me fue ka pantalla en menos de 8...,television Nevir,es,electronics
1,es_0869872,product_es_0922286,reviewer_es_0216771,1,"Horrible, nos tuvimos que comprar otro porque ...",Dinero tirado a la basura con esta compra,es,electronics
2,es_0811721,product_es_0474543,reviewer_es_0929213,1,Te obligan a comprar dos unidades y te llega s...,solo llega una unidad cuando te obligan a comp...,es,drugstore
3,es_0359921,product_es_0656090,reviewer_es_0224702,1,"No entro en descalificar al vendedor, solo pue...",PRODUCTO NO RECIBIDO.,es,wireless
4,es_0068940,product_es_0662544,reviewer_es_0224827,1,Llega tarde y co la talla equivocada,Devuelto,es,shoes

In [30]:
test_data = pd.read_csv('../data/processed/test.csv')
test_data.head()

,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,es_0038754,product_es_0113523,reviewer_es_0580071,1,no me llego el articulo me lo mando por correo...,no me llego,es,wireless
1,es_0748979,product_es_0017036,reviewer_es_0819733,1,"la mensajería horrible, no compro mas",amazon sigue sin cumplir en las entregas,es,home
2,es_0411746,product_es_0138642,reviewer_es_0508607,1,Estoy muy decepcionado con el vendedor ya que ...,ESTAFA EN EL ENVÍO,es,toy
3,es_0786686,product_es_0170887,reviewer_es_0491157,1,Mi valoración no es sobre el producto sino sob...,Estafa de Amazon,es,home
4,es_0429700,product_es_0710642,reviewer_es_0008745,1,Pues tenía interés en este libro y probé la ve...,No conseguí pasar de la portada en Kindle,es,digital_ebook_purchase

In [31]:
validation_data = pd.read_csv('../data/processed/validation.csv')
validation_data.head()

,review_id,product_id,reviewer_id,stars,review_body,review_title,language,product_category
0,es_0417480,product_es_0873923,reviewer_es_0672978,1,"Malisimo, muy grande demasiado aparatoso y mal...",Mala compra,es,wireless
1,es_0180432,product_es_0713146,reviewer_es_0100858,1,No he recibido el pedido no la devolución,No lo he recibido,es,apparel
2,es_0144850,product_es_0356874,reviewer_es_0486447,1,"Tengo que buscar otro sistema, este no funcion...",Que no aprieta bien en el manillar,es,sports
3,es_0339629,product_es_0939832,reviewer_es_0894703,1,Utilicé las brocas de menor diámetro y se me d...,Brocas de mantequilla,es,home_improvement
4,es_0858362,product_es_0489066,reviewer_es_0887663,1,No me gusta su olor a viejo y aspecto malo,No me gusta,es,beauty